<br /><br />
<div id="view-content">
    <h3><?= $this->seitenName ?></h3>
    <p style="text-align: center">
        Bitte wählen Sie einen Mitarbeiter aus, der stellvertretend für Sie Ihren Arbeitszeitbogen bearbeiten darf.
    </p>
    <div id="gridDiv" style="width: 156px; height: <?= 38 + $this->zeilen * 24 ?>px; margin-right: 50%; float: right;"></div>
</div>
<script type="text/javascript">
    dojo.ready(function() {
        var mitarbeiterDaten = <?= $this->mitarbeiterDaten->toJson() ?>;
        
        var dataStore =
            new dojo.data.ItemFileReadStore({ data:mitarbeiterDaten });
        
        var layout =[[
                {'name':'Mitarbeiter','field':'mitarbeitername','width':'147px'},
            ]];
        
        var grid = new dojox.grid.DataGrid({
            store:dataStore,
            structure:layout,
            selectionMode:"none"
        });
        
        grid.placeAt('gridDiv');
        grid.startup();
        
        dojo.connect(grid, "onRowClick", null, function(e){
            var url = "<?=
$this->url(array('vertreter' => ''), 'vertreter', true);
?>";
            var mitarbeiter = grid._getItemAttr(e.rowIndex, 'mitarbeiter');
            url += mitarbeiter;
            console.debug(url);
            location.href = url;
        });
    });
</script>