<br /><br />
<div id="view-content">

    <h3><?= $this->seitenName ?></h3>
    <p>
        <a style="width: 250px; text-align: center" href="
        <?= $this->url(array('controller' => 'bueroleitung', 'action' => 'neu')) ?>
           ">Neuen Mitarbeiter hinzufügen</a>
    </p>
    <div id="gridDiv" style="width: 412px; height: 600px"></div>

</div>

<script type="text/javascript">
    dojo.ready(function() {
        var mitarbeiterDaten = <?= $this->mitarbeiterDaten->toJson() ?>;
        
        var dataStore =
            new dojo.data.ItemFileReadStore({ data:mitarbeiterDaten });
        
        var layout =[[
                {'name':'Mitarbeiter','field':'mitarbeitername','width':'147px'},
                {'name':'Abgeschlossen Bis','field':'abgeschlossen','width':'120px'},
                {'name':'Abgelegt Bis','field':'abgelegt','width':'120px'},
            ]];
        
        var grid = new dojox.grid.DataGrid({
            store:dataStore,
            structure:layout,
            selectionMode:"none"
        });
        
        grid.placeAt('gridDiv');
        grid.startup();
        
        dojo.connect(grid, "onRowClick", null, function(e){
            var url = "<?=
        $this->url(array(
            'benutzername' => '',
                ), 'mitarbeiterdetail', true);
        ?>";
                        var mitarbeiter = grid._getItemAttr(e.rowIndex, 'mitarbeiter');
                        url += mitarbeiter;
                        console.debug(url);
                        location.href = url;
                    });
                });
</script>