<br /><br />
<div id="view-content">
    <h3><?= $this->seitenName ?></h3>
    <?php if ($this->hochschule != 'hfm'): ?>
        <div id="gridDiv" style="width: 881px; height: <?= ($this->tageImMonat + $this->extraZeilen) * 40 + $this->hoheTageImMonat * 16 + 37 ?>px"></div>
    <?php else: ?>    
        <div id="gridDiv" style="width: 830px; height: <?= ($this->tageImMonat + $this->extraZeilen) * 40 + $this->hoheTageImMonat * 16 + 37 ?>px"></div>
    <?php endif; ?>
    <?php if (!$this->jahresabschlussFehlt): ?> 
        <div id="links">
            <p>Saldo Vormonat: <?= $this->saldoBisher; ?>
                <?php if ($this->hatRest): ?>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Rest 2007: <?= $this->saldoBisher2007; ?>)
                <?php endif; ?>
            </p>
            <p>Saldo dieses Monats: <?= $this->saldo; ?></p>
            <p>Saldo gesamt: <?= $this->saldoGesamt; ?>
                <?php if ($this->hatRest): ?>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Rest 2007: <?= $this->saldoGesamt2007; ?>)
                <?php endif; ?>
            </p>
            <p>Resturlaub Vormonat: <?= $this->urlaubBisher; ?>
                <?php if ($this->hatVorjahrRest): ?>
                    <?php if ($this->hochschule != 'hfm'): ?>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Rest Vorjahr: <?= $this->vorjahrRestBisher; ?>)
                    <?php else: ?>
                        + Vorjahr: <?= $this->vorjahrRestBisher; ?> = <?= $this->urlaubZusammenBisher; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
            <p>Urlaub dieses Monats: <?= $this->urlaub; ?></p>
            <p>Resturlaub gesamt: <?= $this->urlaubGesamt; ?>
                <?php if ($this->hatVorjahrRest): ?>
                    <?php if ($this->hochschule != 'hfm'): ?>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Rest Vorjahr: <?= $this->vorjahrRestGesamt; ?>)
                    <?php else: ?>
                        + Vorjahr: <?= $this->vorjahrRestGesamt; ?> = <?= $this->urlaubZusammenGesamt; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
            <?php
            if ($this->azvAnzeigen) {
                echo "<p>AZV-Tage-Rest:  $this->azvRest</p>";
                echo "<p>AZV-Tage dieses Monats:  $this->azvMonat</p>";
            }
            ?>
        </div>
        <div id="rechts">
            <?php
            if ($this->hochschule == 'hfs') {
                foreach ($this->kwZeiten as $kw => $istZeit) {
                    echo "<p>Ist-Arbeitszeit in der KW $kw: ";
                    echo $istZeit->getString();
                    echo '</p>';
                }
            }
            ?>
        </div>
    <?php else: ?>
        <p>
            Der Mitarbeiter hat das Vorjahr noch nicht abgeschlossen, also können keine korrekten
            Salden angezeigt werden.
        </p>
    <?php endif; ?>
</div>

<script type="text/javascript">
    dojo.ready(function() {
    var monatsDaten = <?= $this->monatsDaten->toJson() ?>;
            var dataStore =
            new dojo.data.ItemFileReadStore({ data:monatsDaten });
            var layout = [[
            {'name':'Datum', 'field':'datum', 'width':'87px'},
            {'name':'Beginn', 'field':'beginn', 'width':'55px'},
            {'name':'Ende', 'field':'ende', 'width':'55px'},
            {'name':'Dienstbefreiung', 'field':'befreiung', 'width':'120px'},
            {'name':'Bemerkung', 'field':'bemerkung', 'width':'220px'},
<?php if ($this->hochschule != 'hfm'): ?>
                {'name':'ohne Pause', 'field':'pause', 'width':'43px', 'styles':'text-align: center;'},
<?php endif; ?>
            {'name':'An- wesend', 'field':'anwesend', 'width':'55px'},
            {'name':'Ist', 'field':'ist', 'width':'55px'},
            {'name':'Soll', 'field':'soll', 'width':'55px', 'formatter': function(val, rowIdx, cell) {cell.customClasses.push('erg'); return val; }},
            {'name':'+/-', 'field':'saldo', 'width':'55px'},
            ]];
            var grid = new dojox.grid.DataGrid({
            store:dataStore,
                    structure:layout,
                    selectionMode:"none"
            });
            dojo.connect(grid, "onStyleRow", function(row){
            var item = grid.getItem(row.index);
                    if (item) {
            var istFeiertag = dataStore.getValue(item, "feiertag", null);
                    if (!!istFeiertag) {
            row.customStyles += "color: #fe3c1a;";
            }
            }
            grid.focus.styleRow(row);
                    grid.edit.styleRow(row);
            });
            grid.placeAt('gridDiv');
            grid.startup();
    });
</script>