<br /><br />
<div id="view-content">
    <h3><?= $this->seitenName ?></h3>
    <a style="width: 280px; text-align: center" href="<?= $this->urlAblegen?>">Monat ablegen</a>
    <br/>
    <a style="width: 280px; text-align: center" href="<?= $this->urlZurueck?>">Monatsabschluss zurücknehmen</a>
    <br/>
    <a style="width: 280px; text-align: center" href="<?= $this->urlAnzeigen?>">Monat anzeigen</a>
</div>