<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headScript(); ?>
    </head>
        <body>
        <div id="Seite">
            <div id="Kopfzeile">
                <h1>Zeiterfassungsbogen</h1>
                <h2>Übersicht 2012</h2>
            </div>
            <div id="Navigation">
                <h2 id="Navigation">Hans Mustermann</h2>
                <ul id="Navigation">
                    <li><a href="uebersicht.html"
                           onmouseover="fopen('Nav_Jahre')"
                           onmouseout="fclosetime()">Übersicht</a>
                        <ul id="Nav_Jahre"
                            onmouseover="fcancelclosetime()"
                            onmouseout="fclosetime()">
                            <li><a href="#" >2011</a></li>
                            <li><a href="#" style="font-weight:bold">2012</a></li>
                        </ul>
                    </li>
                    <li><a href="#"
                           onmouseover="fopen('Nav_Monate')"
                           onmouseout="fclosetime()">Monate</a>
                        <ul id="Nav_Monate"
                            onmouseover="fcancelclosetime()"
                            onmouseout="fclosetime()">
                            <li><a href="januar.html">Januar</a></li>
                            <li><a href="februar.html" >Februar</a></li>
                            <li><a href="maerz.html" >März</a></li>
                            <li><a href="april.html" >April</a></li>
                            <li><a href="mai.html" >Mai</a></li>
                            <li><a href="juni.html" >Juni</a></li>
                            <li><a href="juli.html" >Juli</a></li>
                            <li><a href="august.html" >August</a></li>
                            <li><a href="september.html" >September</a></li>
                            <li><a href="oktober.html" >Oktober</a></li>
                            <li><a href="november.html" >November</a></li>
                            <li><a href="dezember.html" >Dezember</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Logout</a></li>
                </ul>
                <div style="clear:both"></div>
            </div>
            <div id="Inhalt">
    <?= $this->layout()->content ?>
            </div>

            <div id="Fusszeile">&copy; 2012 ServiceCenter IT. Version: 0.1</div>
        </div>
    </body>
</html>