<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headScript(); ?>
        <?php
        if ($this->dojo()->isEnabled()) {
            $this->dojo()->setLocalPath('/javascript/dojo/dojo.js')
                    ->addStyleSheetModule('dijit.themes.tundra')
                    ->addStyleSheet('/javascript/dojox/grid/resources/Grid.css')
                    ->addStyleSheet('/javascript/dojox/grid/resources/tundraGrid.css')
                    ->addStyleSheet('/javascript/dojox/widget/ColorPicker/ColorPicker.css');
            echo $this->dojo();
        }
        ?>

        <?php
        $this->setHelperPath(APPLICATION_PATH . '/layouts/helpers');
        $farben = $this->farbe();
        ?>
        <style type="text/css">
            div#Kopfzeile {
                background-color: <?= $farben->kopf ?>;
            }
            div.Navigation {
                background-color: <?= $farben->kopf ?>;
            }
            ul.Navigation li ul a {
                background-color: <?= $farben->kopf ?>;
            }
            div#Fusszeile {
                background-color: <?= $farben->kopf ?>;
            }
            .tundra .dojoxGridRowOdd {
                background-color: <?= $farben->kopf ?> !important;
            }
            ul.Navigation li a:hover {
                background-color: <?= $farben->hoover ?>;
            }
            a:hover {
                background-color: <?= $farben->hoover ?>;
            }
            div#Kopfzeile {
                border-color: <?= $farben->link ?>;
            }
            div.Navigation {
                border-color: <?= $farben->link ?>;
            }
            ul.Navigation li a {
                background-color: <?= $farben->link ?>;
            }
            ul.Navigation li ul {
                border-color: <?= $farben->link ?>;
            }
            a {
                background-color: <?= $farben->link ?>;
            }
            a.no-link:hover {
                background-color: <?= $farben->link ?>;
            }
            th.mituebersicht {
                background-color: <?= $farben->link ?>;
            }
            div#Fusszeile {
                border-color: <?= $farben->link ?>;
            }
            .tundra .dojoxGridRowOver {
                background-color: <?= $farben->link ?> !important;
            }
            .tundra .dojoxGridRowOver .dojoxGridCell {
                background-color: <?= $farben->zeile ?> !important;
            }
        </style>

    </head>
    <body class="tundra">
        <div id="Seite">
            <div id="Kopfzeile">
                <h1><a href="
                    <?= $this->baseUrl('') ?>
                       "><?= $this->placeholder('Zend_View_Helper_HeadTitle') ?></a></h1>
                <h2><?= $this->seitenName ?></h2>
            </div>
            <div class="Navigation">
                <?= $this->render('nav.phtml') ?>
            </div>
            <div id="Inhalt">
                <?= $this->layout()->content ?>
            </div>

            <div id="Fusszeile">&copy; 2012 - 2017 ServiceCenter IT. Version: <?= $this->version ?></div>
        </div>
    </body>
</html>