<h2 class="Navigation"><?= $this->name ?></h2>
<ul class="Navigation">
    <li><a href="uebersicht.html"
           onmouseover="azeboopen('Nav_Jahre')"
           onmouseout="azeboclosetime()">Übersicht</a>
        <ul id="Nav_Jahre"
            onmouseover="azebocancelclosetime()"
            onmouseout="azeboclosetime()">
            <li><a href="#" >2011</a></li>
            <li><a href="#" style="font-weight:bold">2012</a></li>
        </ul>
    </li>
    <li><a href="#"
           onmouseover="azeboopen('Nav_Monate')"
           onmouseout="azeboclosetime()">Monate</a>
        <ul id="Nav_Monate"
            onmouseover="azebocancelclosetime()"
            onmouseout="azeboclosetime()">
                <? $this->setHelperPath(APPLICATION_PATH . '/layouts/helpers') ?>
                <?= $this->monatsliste() ?>
        </ul>
    </li>
    <li><a href="
        <?= $this->url(array('controller' => 'login', 'action' => 'logout',)) ?>
           ">Abmelden</a></li>
</ul>
<div style="clear:both"></div>