<?php $this->setHelperPath(APPLICATION_PATH . '/layouts/helpers', 'Zend_View_Helper_') ?>

<h2 class="Navigation"><?= $this->name() ?></h2>
<ul class="Navigation">
    <?= $this->bueroleitung() ?>
    <li>
        <a
            href="<?php
            $date = new Zend_Date();
            $url = $this->url(array('jahr' => $date->toString('yyyy'),), 'uebersicht', true);
            echo $url;
            ?>"
            onmouseover="azeboopen('Nav_Jahre')"
            onmouseout="azeboclosetime()"
            <?php if ($url == $this->requestURI) {
                echo 'style="font-weight:bold;"';
            } ?>
            >
            Übersicht
        </a>
        <ul id="Nav_Jahre"
            onmouseover="azebocancelclosetime()"
            onmouseout="azeboclosetime()"><?= "\n" . $this->jahresliste() ?>
        </ul>
    </li>
    <li>
        <a href="<?php
        $url = $this->url(array(
            'jahr' => $date->toString('yyyy'),
            'monat' => $date->toString('M'),
                ), 'monat', true);
        echo $url;
        ?>"
           onmouseover="azeboopen('Nav_Monate')"
           onmouseout="azeboclosetime()"
<?php if ($url == $this->requestURI) {
    echo 'style="font-weight:bold;"';
} ?>
           >
            Monate
        </a>
        <ul id="Nav_Monate"
            onmouseover="azebocancelclosetime()"
            onmouseout="azeboclosetime()"><?= "\n" . $this->monatsliste() ?>
        </ul>
    </li>
    <li>
        <a href="<?= $this->url(array('controller' => 'login', 'action' => 'logout',), 'default', true) ?>">
            Abmelden
        </a>
    </li>
</ul>
<div style="clear:both"></div>