<br /><br />
<div id="view-content">
    <h3><?= $this->seitenName ?></h3>
    <div id="view-content">
        <div id="gridObenDiv" style="width: 881px; height: <?= ($this->tag - 1 + $this->extraZeilenOben) * 40 + $this->hoheTageImMonatOben * 16 + 37 ?>px"></div>
        <a name="form"></a>
        <h4>Daten für den <?= $this->tag; ?>.<?= $this->monat; ?>. bearbeiten</h4>
        <?= $this->tagForm; ?>

        <div id="gridUntenDiv" style="width: 881px; height: <?= ($this->tageImMonat - $this->tag + $this->extraZeilenUnten) * 40 + $this->hoheTageImMonatUnten * 16 + 37 ?>px"></div>
    </div>
    <p>Saldo der abgeschlossenen Monate: <?= $this->saldoBisher; ?></p>
</div>
<script type="text/javascript">
    dojo.ready(function() {
        var layout =[[
                {'name':'Datum','field':'datum','width':'87px'},
                {'name':'Beginn','field':'beginn','width':'55px'},
                {'name':'Ende','field':'ende','width':'55px'},
                {'name':'Dienstbefreiung','field':'befreiung','width':'120px'},
                {'name':'Bemerkung','field':'bemerkung','width':'220px'},
                {'name':'ohne Pause','field':'pause','width':'43px','styles':'text-align: center;'},
                {'name':'An- wesend','field':'anwesend','width':'55px'},
                {'name':'Ist','field':'ist','width':'55px'},
                {'name':'Soll','field':'soll','width':'55px'},
                {'name':'+/-','field':'summe','width':'55px'},
            ]];
        
<? if ($this->monatsDatenOben !== null): ?>
                
            var monatsDatenOben = <?= $this->monatsDatenOben->toJson() ?>;
         
            var dataStoreOben =
                new dojo.data.ItemFileReadStore({ data:monatsDatenOben });
                
            var gridOben = new dojox.grid.DataGrid({
                store:dataStoreOben,
                structure:layout,
                selectionMode:"none"
            });
                 
            dojo.connect(gridOben, "onStyleRow", function(row){
                var item = gridOben.getItem(row.index);
                if(item) {
                    var istFeiertag = dataStoreOben.getValue(item,"feiertag",null);
                    if(!!istFeiertag) {
                        row.customStyles += "color: #fe3c1a;";
                    }
                }
                gridOben.focus.styleRow(row);
                gridOben.edit.styleRow(row);
            });
                
            gridOben.placeAt('gridObenDiv');
            gridOben.startup();
                    
            dojo.connect(gridOben, "onRowClick", null, function(e){
                var url = "<?= $this->url(array('monat' => $this->monat, 'jahr' => $this->jahr,), 'monat', true); ?>";
                url += "/" + gridOben._getItemAttr(e.rowIndex, 'tag') + "#form";
                location.href = url;
            });        
<? endif; ?>
<? if ($this->monatsDatenUnten !== null): ?>
                
            var monatsDatenUnten = <?= $this->monatsDatenUnten->toJson() ?>;
         
            var dataStoreUnten =
                new dojo.data.ItemFileReadStore({ data:monatsDatenUnten });
                
            var gridUnten = new dojox.grid.DataGrid({
                store:dataStoreUnten,
                structure:layout,
                selectionMode:"none"
            });
                 
            dojo.connect(gridUnten, "onStyleRow", function(row){
                var item = gridUnten.getItem(row.index);
                if(item) {
                    var istFeiertag = dataStoreUnten.getValue(item,"feiertag",null);
                    if(!!istFeiertag) {
                        row.customStyles += "color: #fe3c1a;";
                    }
                }
                gridUnten.focus.styleRow(row);
                gridUnten.edit.styleRow(row);
            });
                
            gridUnten.placeAt('gridUntenDiv');
            gridUnten.startup();
                    
            dojo.connect(gridUnten, "onRowClick", null, function(e){
                var url = "<?= $this->url(array('monat' => $this->monat, 'jahr' => $this->jahr,), 'monat', true); ?>";
                url += "/" + gridUnten._getItemAttr(e.rowIndex, 'tag') + "#form";
                location.href = url;
            });        
<? endif; ?>
        var tip = new dijit.Tooltip({
            label: '<p>Falls gewünscht, fügen Sie bitte zunächst den Nachmittag\
    hinzu, und tragen Sie dann Ihre Daten für diesen Arbeitstag ein.</p>',
            showDelay: 50,
            connectId: ["nachmittag"]
        });
    });
 
</script>
