<div id="view-content">
    <h3><?= $this->seitenName ?></h3>

    <div id="gridDiv" style="width: 970px; height: 900px"></div>
</div>

<script type="text/javascript">
    dojo.ready(function() {
        var monatsDaten = <?= $this->monatsDaten->toJson() ?>;
 
        var dataStore =
            new dojo.data.ItemFileReadStore(
        { data:monatsDaten }
    );
        
        var layout =[[
                {'name':'Datum','field':'datum','width':'120px'},
                {'name':'Beginn','field':'beginn','width':'60px'},
                {'name':'Ende','field':'ende','width':'60px'},
                {'name':'Dienstbefreiung','field':'befreiung','width':'120px'},
                {'name':'Bemerkung','field':'bemerkung','width':'220px'},
                {'name':'ohne Pause','field':'pause','width':'50px'},
                {'name':'Anwesend','field':'anwesend','width':'75px'},
                {'name':'Ist','field':'ist','width':'60px'},
                {'name':'Soll','field':'soll','width':'60px'},
                {'name':'+/-','field':'summe','width':'60px'},
            ]];
        
        var grid = new dojox.grid.DataGrid({
            store:dataStore,
            structure:layout
        });
         
        dojo.connect(grid, "onStyleRow", function(row){
            var item = grid.getItem(row.index);
            if(item) {
                var istFeiertag = dataStore.getValue(item,"feiertag",null);
                if(!!istFeiertag) {
                    row.customStyles += "color: #fe3c1a;";
                }
            }
            grid.focus.styleRow(row);
            grid.edit.styleRow(row);
        });
         
        grid.placeAt('gridDiv');
        grid.startup();
               
        dojo.connect(grid, "onRowClick", null, function(e){
            console.debug("Reihe geclickt!");
            console.debug(e.rowIndex);
        });   
    });
</script>