<div id="view-content">
    <h3><?= $this->seitenName ?></h3>

    <div id="gridDiv" style="width: 874px; height: <?= $this->tageImMonat * 41 + 55 ?>px"></div>
</div>

<script type="text/javascript">
    dojo.ready(function() {
        var monatsDaten = <?= $this->monatsDaten->toJson() ?>;
 
        var dataStore =
            new dojo.data.ItemFileReadStore({ data:monatsDaten });
        
        var layout =[[
                {'name':'Datum','field':'datum','width':'80px'},
                {'name':'Beginn','field':'beginn','width':'55px'},
                {'name':'Ende','field':'ende','width':'55px'},
                {'name':'Dienstbefreiung','field':'befreiung','width':'120px'},
                {'name':'Bemerkung','field':'bemerkung','width':'220px'},
                {'name':'ohne Pause','field':'pause','width':'43px'},
                {'name':'An- wesend','field':'anwesend','width':'55px'},
                {'name':'Ist','field':'ist','width':'55px'},
                {'name':'Soll','field':'soll','width':'55px'},
                {'name':'+/-','field':'summe','width':'55px'},
            ]];
        
        var grid = new dojox.grid.DataGrid({
            store:dataStore,
            structure:layout,
            selectionMode:"none"
        });
         
        dojo.connect(grid, "onStyleRow", function(row){
            var item = grid.getItem(row.index);
            if(item) {
                var istFeiertag = dataStore.getValue(item,"feiertag",null);
                if(!!istFeiertag) {
                    row.customStyles += "color: #fe3c1a;";
                }
            }
            grid.focus.styleRow(row);
            grid.edit.styleRow(row);
        });
         
        grid.placeAt('gridDiv');
        grid.startup();
               
        dojo.connect(grid, "onRowClick", null, function(e){
            console.debug("Reihe geclickt!");
            console.debug(e.rowIndex);
            
            var url = "<?=$this->url(array(
                'monat' => $this->monat,
                'jahr' => $this->jahr,
                    ), 'monat', true); ?>";
            var tag = e.rowIndex + 1;
            url += "/" + tag;
            console.debug(url);
            location.href = url;
        });   
    });
</script>