<div id="view-content">
    <h3><?= $this->seitenName ?></h3>

    <div id="gridDiv" style="width: 881px; height: <?= ($this->tageImMonat + $this->extraZeilen) * 40 + $this->hoheTageImMonat * 16 + 37 ?>px"></div>
    <p>Saldo der abgeschlossen Monate: <?= $this->saldoBisher; ?></p>
    <p>Saldo dieses Monats: <?= $this->saldo; ?></p>
    <p>Resturlaub bisher: <?= $this->urlaubBisher; ?></p>
    <p>Urlaub dieses Monats: <?= $this->urlaub; ?></p>
    <a name="monatForm"></a>
    <?= $this->monatForm; ?>
</div>

<script type="text/javascript">
    dojo.ready(function() {
        var monatsDaten = <?= $this->monatsDaten->toJson() ?>;
 
        var dataStore =
            new dojo.data.ItemFileReadStore({ data:monatsDaten });
        
        var layout =[[
                {'name':'Datum','field':'datum','width':'87px'},
                {'name':'Beginn','field':'beginn','width':'55px'},
                {'name':'Ende','field':'ende','width':'55px'},
                {'name':'Dienstbefreiung','field':'befreiung','width':'120px'},
                {'name':'Bemerkung','field':'bemerkung','width':'220px'},
                {'name':'ohne Pause','field':'pause','width':'43px',styles:'text-align: center;'},
                {'name':'An- wesend','field':'anwesend','width':'55px'},
                {'name':'Ist','field':'ist','width':'55px'},
                {'name':'Soll','field':'soll','width':'55px'},
                {'name':'+/-','field':'saldo','width':'55px'},
            ]];
        
        var grid = new dojox.grid.DataGrid({
            store:dataStore,
            structure:layout,
            selectionMode:"none"
        });
         
        dojo.connect(grid, "onStyleRow", function(row){
            var item = grid.getItem(row.index);
            if(item) {
                var istFeiertag = dataStore.getValue(item,"feiertag",null);
                if(!!istFeiertag) {
                    row.customStyles += "color: #fe3c1a;";
                }
            }
            grid.focus.styleRow(row);
            grid.edit.styleRow(row);
        });
         
        grid.placeAt('gridDiv');
        grid.startup();
               
<? if ($this->bearbeitbar): ?>       
                    dojo.connect(grid, "onRowClick", null, function(e){
                        var url = "<?=
    $this->url(array(
        'monat' => $this->monat,
        'jahr' => $this->jahr,
            ), 'monat', true);
    ?>";
                                    var tag = grid._getItemAttr(e.rowIndex, 'tag');
                                    url += "/" + tag + "#form";
                                    console.debug(url);
                                    location.href = url;
                                }); 
<? endif ?>
        
                var tip = new dijit.Tooltip({
                    label: '<p>Der Monatsabschluss kann nicht mehr rückgängig gemacht werden!</p>',
                    showDelay: 50,
                    connectId: ["abschliessen"]
                });
            });
    
    
</script>