<br /><br />
<div id="view-content">
    <h3><?= $this->seitenName ?></h3>
    <div id="gridDiv" style="width: 393px; height: 326px"></div>
</div>
<?
if ($this->hochschule == 'hfs') {
    echo "<p style=\"width: 180px; text-align: center; margin-bottom: 0px;\"><a href  =";
    //echo $this->url(array('mitarbeiter' => $this->mitarbeiter), 'vertreter', true);
    echo $this->url(array(
        'controller' => 'uebersicht',
        'action' => 'vertreter',
        ), 'default', true);
    echo ">Vertreter einrichten</a></p>";
}
?>

<script type="text/javascript">
    dojo.ready(function() {
        var jahresDaten = <?= $this->jahresDaten->toJson() ?>;
        
        var dataStore =
            new dojo.data.ItemFileReadStore({ data:jahresDaten });
        
        var layout =[[
                {'name':'Monat','field':'monat','width':'90px'},
                {'name':'Abge- schlossen','field':'abgeschlossen','width':'90px'},
                {'name':'Saldo des Monats','field':'saldo','width':'90px'},
                {'name':'Urlaubstage des Monats','field':'urlaub','width':'90px'},
            ]];
        
        var grid = new dojox.grid.DataGrid({
            store:dataStore,
            structure:layout,
            selectionMode:"none"
        });
        
        grid.placeAt('gridDiv');
        grid.startup();
    });

</script>